// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IconMdiGithub: typeof import('~icons/mdi/github')['default']
    MenuLink: typeof import('./src/components/top-nav/MenuLink.vue')['default']
    TopNav: typeof import('./src/components/top-nav/index.vue')['default']
    UserCenter: typeof import('./src/components/top-nav/UserCenter.vue')['default']
  }
}

export {}
